### ISSUE TITLE
Multiple Tokens

### ISSUE THREAD

**Issue by galmog** [NeuralTextualInversion/NeTI#6]
Hi! Thanks for the great paper!
Does the current code support generating images with 2+ personalized tokens? I can't seem to find a way to do it.

**Comment by NeuralTextualInversion** [comment]
The current code doesn't support multiple objects, but this can be done by extending the PromptManager class. Specifically, you'll want to make a change to the following line: 
https://github.com/NeuralTextualInversion/NeTI/blob/ad8e492298344371531e678ad939144fb1dbb071/prompt_manager.py#L36
Here, we add the concept's placeholder token into the `text` string. What you could do is pass multiple place holder tokens and then add each of them to the desired place in the text. 
For example, if you had: 
```python
text = "A photo of a {} sitting next to a {}"
concept_1_placeholder = "<cat-toy>"
concept_2_placeholder = "<colorful-teapot>"
text = text.format(concept_1_placeholder, concept_2_placeholder)
```
You'll also need to make some changes to the [NeTICLIPTextEmbeddings](https://github.com/NeuralTextualInversion/NeTI/blob/main/models/net_clip_text_embedding.py#L11) class to embed each concept using is corresponding mapper. 
So, it's possible, but does requiring digging into the code a bit. 
In general, NeTI doesn't perform too well for generating images with multiple concepts. This is a current limitation of the work and a discussion on this will be added to the paper revision in the coming weeks.

**Comment by Derry-Xing** [comment]
raise ValueError("The super category token must be a single token.")
ValueError: The super category token must be a single token.

Dear Author, how to solve the above error?

**Comment by yuval-alaluf** [comment]
What is the supercategory that you chose? What most likely caused this is that you chose a word that is split into two tokens in the tokenization process. You'll want to make sure that the super-category is a single token .

**Comment by yja1** [comment]
why  NeTI doesn't perform well for generating images with multiple concepts?
