### ISSUE TITLE
10 picture to train character

### ISSUE THREAD

**Issue by Middle-Night** [NeuralTextualInversion/NeTI#7]
Hello, in your project, I trained the characters(a girl) with 3 pictures and 10 pictures respectively. I found that in the results of training with 10 pictures, the faces of the characters in the pictures were processed worse. Why？

**Comment by yuval-alaluf** [comment]
There could be multiple reasons for this. In the original textual inversion paper, we showed that adding additional images may not necessarily help in the training process. For example, if the images you add contain very different (or similar) backgrounds or if the differences between the images representing the subject are very large, this could also harm performance. 
Are the new images you added relatively similar or are there significant differences between them?
