### ISSUE TITLE
truncation_idx is None

### ISSUE THREAD

**Issue by yja1** [NeuralTextualInversion/NeTI#8]
test teddybear model from 'https://drive.google.com/drive/folders/1fRLRpl-IRoKbHqQt6hQ7yFx9laUIa_-A'
  File "scripts/inference.py", line 97, in main
    for truncation_idx in infer_cfg.truncation_idxs:
TypeError: 'NoneType' object is not iterable

**Comment by yuval-alaluf** [comment]
I believe the correct fix would be to change the following lines: 
```python
if type(self.truncation_idxs) == int:
            self.truncation_idxs = [self.truncation_idxs]
```
to
```python
if self.truncation_idxs is None or type(self.truncation_idxs) == int:
            self.truncation_idxs = [self.truncation_idxs]
```
Can you let me know if this solves the issue?
